set_property IOSTANDARD LVCMOS33 [get_ports SW_R]
set_property IOSTANDARD LVCMOS33 [get_ports Dinout_top]

set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_R[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_R[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_R[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_R[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_R[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_R[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_R[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_R[0]}]
set_property PACKAGE_PIN U14 [get_ports {LED_R[7]}]
set_property PACKAGE_PIN U19 [get_ports {LED_R[6]}]
set_property PACKAGE_PIN W22 [get_ports {LED_R[5]}]
set_property PACKAGE_PIN V22 [get_ports {LED_R[4]}]
set_property PACKAGE_PIN U21 [get_ports {LED_R[3]}]
set_property PACKAGE_PIN U22 [get_ports {LED_R[2]}]
set_property PACKAGE_PIN T21 [get_ports {LED_R[1]}]
set_property PACKAGE_PIN T22 [get_ports {LED_R[0]}]
set_property PACKAGE_PIN Y9 [get_ports clk]
set_property PACKAGE_PIN Y5 [get_ports Dinout_top]
set_property PULLUP true [get_ports Dinout_top]
set_property PACKAGE_PIN T18 [get_ports rst]
set_property PACKAGE_PIN R18 [get_ports SW_R]  #•k¡‰

set_property PACKAGE_PIN R18 [get_ports SW_R]
